# -*- coding: utf-8 -*-
"""
Created on Tue Oct 11 00:25:41 2022

@author: jef
"""

VERSION = "V2.0"

LOG_DIRECTORY = "log"
DEFAULT_LOG_LEVEL = "DEBUG"
DATE_SERIAL_FORMATTER = "%d-%m-%Y %H:%M:%S"
DATE_DISPLAY_FORMATTER = "%d/%m/%Y %H:%M:%S"

DEFAULT_LATITUDE = "N45°23'"
DEFAULT_LONGITUDE = "E005°23'"
DEFAULT_SPEED = 5.0
DEFAULT_COURSE = 0.0
DEFAULT_EYE_HEIGHT = 2.0
